# Generated by Django 5.2.8 on 2026-01-09 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('primary_color', models.CharField(default='#3b82f6', max_length=7)),
                ('glass_intensity', models.IntegerField(default=82)),
                ('glass_blur', models.IntegerField(default=18)),
                ('ambient_shadow', models.IntegerField(default=55)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='appuser',
            name='cpf',
            field=models.CharField(max_length=14),
        ),
        migrations.CreateModel(
            name='InAppWarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('info', 'Informativo'), ('success', 'Sucesso'), ('warning', 'Aviso'), ('critical', 'Crítico')], default='info', max_length=20)),
                ('whatsapp_btn', models.CharField(blank=True, max_length=20, null=True)),
                ('sticky', models.BooleanField(default=False)),
                ('show_home', models.BooleanField(default=False)),
                ('target_cpfs', models.TextField(blank=True, help_text='Separados por vírgula')),
                ('target_contracts', models.TextField(blank=True, help_text='Separados por vírgula')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_app_warnings', to='core.provider')),
            ],
        ),
        migrations.CreateModel(
            name='AppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_shortcuts', models.JSONField(blank=True, default=list)),
                ('active_tools', models.JSONField(blank=True, default=list)),
                ('social_links', models.JSONField(blank=True, default=list)),
                ('update_warning_active', models.BooleanField(default=False)),
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='app_config', to='core.provider')),
            ],
        ),
        migrations.AddField(
            model_name='appuser',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_users', to='core.provider'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.provider'),
        ),
        migrations.AddField(
            model_name='notification',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.provider'),
        ),
        migrations.AlterUniqueTogether(
            name='appuser',
            unique_together={('provider', 'cpf')},
        ),
    ]
