# Generated by Django 5.2.8 on 2026-01-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_provider_alter_appuser_cpf_inappwarning_appconfig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
