# Generated by Django 5.2.8 on 2026-01-09 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_provider_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='cnpj',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
