# Generated by Django 5.2.8 on 2026-01-09 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_provider_cnpj_provider_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='sgp_token',
            field=models.CharField(blank=True, help_text='Token de autenticação para webhooks do SGP.', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='sgp_token_created_at',
            field=models.DateTimeField(blank=True, help_text='Data de criação do token SGP.', null=True),
        ),
    ]
