# Generated by Django 5.2.4 on 2026-01-12 06:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_provider_sgp_token_provider_sgp_token_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='last_active',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
