# Generated by Django 5.2.4 on 2026-01-12 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_device_created_at_alter_device_last_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='core.provider'),
        ),
        migrations.AlterField(
            model_name='device',
            name='push_token',
            field=models.CharField(blank=True, help_text='FCM/Expo Token', max_length=255, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together={('provider', 'push_token')},
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('recipients_count', models.IntegerField()),
                ('success_count', models.IntegerField()),
                ('failure_count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='core.provider')),
            ],
        ),
    ]
