# Generated by Django 5.2.4 on 2026-01-14 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_device_provider_alter_device_push_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='customer_id',
            field=models.CharField(blank=True, db_index=True, help_text='ID do cliente no SGP', max_length=50, null=True),
        ),
    ]
