# Generated by Django 5.2.4 on 2026-01-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_aichatsession_aichatmessage_networktelemetry'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gemini_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração Global',
                'verbose_name_plural': 'Configurações Globais',
            },
        ),
        migrations.AddField(
            model_name='provider',
            name='sgp_url',
            field=models.URLField(blank=True, help_text='URL base do SGP (ex: https://r7fibra.sgp.tsmx.com.br)', max_length=255, null=True),
        ),
    ]
