# Generated by Django 5.2.4 on 2026-01-18 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_systemsettings_provider_sgp_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='sgp_app_name',
            field=models.CharField(blank=True, help_text='Nome do App cadastrado no SGP (ex: webchat)', max_length=64, null=True),
        ),
    ]
