# Generated by Django 5.2.4 on 2026-01-19 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_provider_sgp_app_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Plano')),
                ('type', models.CharField(choices=[('FIBRA', 'Fibra Óptica'), ('RADIO', 'Rádio'), ('CABO', 'Cabo')], default='FIBRA', max_length=20, verbose_name='Tipo de Tecnologia')),
                ('download_speed', models.IntegerField(verbose_name='Velocidade Download (Mbps)')),
                ('upload_speed', models.IntegerField(verbose_name='Velocidade Upload (Mbps)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Mensal')),
                ('description', models.TextField(blank=True, help_text='O que está incluso no plano', verbose_name='Descrição Detalhada')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='core.provider')),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
            },
        ),
    ]
