# Generated by Django 5.2.4 on 2026-01-22 00:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome do template', max_length=255)),
                ('title', models.CharField(help_text='Título da notificação', max_length=255)),
                ('body', models.TextField(help_text='Corpo da mensagem')),
                ('type', models.CharField(choices=[('info', 'Informativo'), ('promo', 'Promocional'), ('warning', 'Aviso')], default='info', help_text='Tipo da notificação', max_length=20)),
                ('image_url', models.URLField(blank=True, help_text='URL da imagem (opcional)', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_templates', to='core.provider')),
            ],
            options={
                'verbose_name': 'Template de Notificação',
                'verbose_name_plural': 'Templates de Notificação',
                'ordering': ['-updated_at'],
            },
        ),
    ]
