# Generated by Django 5.2.4 on 2026-01-22 01:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_add_notification_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('type', models.CharField(choices=[('info', 'Informativo'), ('promo', 'Promocional'), ('warning', 'Aviso')], default='info', max_length=20)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('scheduled_at', models.DateTimeField(help_text='Data e hora agendada para envio')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('sent', 'Enviada'), ('failed', 'Falhou'), ('cancelled', 'Cancelada')], default='pending', max_length=20)),
                ('segment_type', models.CharField(default='all', max_length=20)),
                ('segment_tags', models.CharField(blank=True, max_length=500, null=True)),
                ('segment_search', models.CharField(blank=True, max_length=255, null=True)),
                ('sent_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_notifications', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_notifications', to='core.provider')),
            ],
            options={
                'verbose_name': 'Notificação Agendada',
                'verbose_name_plural': 'Notificações Agendadas',
                'ordering': ['scheduled_at'],
                'indexes': [models.Index(fields=['status', 'scheduled_at'], name='core_schedu_status_924899_idx')],
            },
        ),
    ]
