# Generated by Django 5.2.4 on 2026-01-22 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_add_scheduled_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='webhook_url',
            field=models.URLField(blank=True, help_text='URL customizada do webhook para integração SGP', max_length=500, null=True),
        ),
    ]
