# Generated by Django 5.2.4 on 2026-01-22 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_add_webhook_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='sgp_app_name',
            field=models.CharField(blank=True, help_text='Nome do App cadastrado no SGP (ex: webchat)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='sgp_token',
            field=models.CharField(blank=True, help_text='Token de autenticação para webhooks do SGP.', max_length=255, null=True, unique=True),
        ),
    ]
