# Generated by Django 5.2.4 on 2026-01-23 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_provider_sgp_app_name_alter_provider_sgp_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='sgp_token',
            field=models.CharField(blank=True, help_text='Token de autenticação para webhooks do SGP.', max_length=500, null=True, unique=True),
        ),
    ]
