# Generated by Django 6.0.2 on 2026-02-11 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='pppoe_login',
            field=models.CharField(blank=True, db_index=True, help_text='Login PPPoE do cliente', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appconfig',
            name='active_shortcuts',
            field=models.JSONField(blank=True, default=list, help_text="Lista de atalhos ativos na Home (Ex: ['FATURAS', 'PLANOS'])"),
        ),
        migrations.AlterField(
            model_name='appconfig',
            name='active_tools',
            field=models.JSONField(blank=True, default=list, help_text="Lista de ferramentas ativas no Hub (Ex: ['MEU WI-FI', 'FAST TEST'])"),
        ),
    ]
