# Generated by Django 6.0.2 on 2026-02-11 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_appuser_pppoe_login_alter_appconfig_active_shortcuts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='wifi_password_2g',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='wifi_password_5g',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='wifi_ssid_2g',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='wifi_ssid_5g',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
