# Generated by Django 6.0.2 on 2026-02-11 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_appuser_wifi_password_2g_appuser_wifi_password_5g_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='genieacs_password',
            field=models.CharField(blank=True, help_text='Senha do GenieACS NBI', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='genieacs_url',
            field=models.URLField(blank=True, help_text='URL base do GenieACS (ex: http://tr069.asnetfibra.net.br:7557)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='genieacs_user',
            field=models.CharField(blank=True, help_text='Usuário do GenieACS NBI', max_length=255, null=True),
        ),
    ]
