# Generated by Django 6.0.2 on 2026-02-11 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_provider_genieacs_password_provider_genieacs_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='shortcut_wifi',
            field=models.BooleanField(default=True, verbose_name='Atalho Wi-Fi'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='tool_connected_devices',
            field=models.BooleanField(default=True, verbose_name='Ferramenta Dispositivos Conectados'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='tool_faturas',
            field=models.BooleanField(default=True, verbose_name='Ferramenta Faturas'),
        ),
    ]
