# Generated by Django 6.0.2 on 2026-02-11 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_appconfig_shortcut_wifi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='tool_auto_unlock',
            field=models.BooleanField(default=True, verbose_name='Ferramenta Desbloqueio'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='tool_cameras',
            field=models.BooleanField(default=False, verbose_name='Ferramenta Câmeras'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='tool_speed_test',
            field=models.BooleanField(default=True, verbose_name='Ferramenta Speed Test'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='tool_wifi',
            field=models.BooleanField(default=True, verbose_name='Ferramenta Meu Wi-Fi'),
        ),
    ]
