# Generated by Django 6.0.2 on 2026-02-11 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_appconfig_tool_auto_unlock_appconfig_tool_cameras_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='genieacs_device_id',
            field=models.CharField(blank=True, help_text='ID do dispositivo no GenieACS (cache)', max_length=255, null=True),
        ),
    ]
