# Generated by Django 6.0.2 on 2026-02-11 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_appuser_genieacs_device_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='modem_external_ip',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='modem_last_sync_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='modem_manufacturer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='modem_model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='modem_uptime_seconds',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]

