# Generated by Django 6.0.2 on 2026-02-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_device_push_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inappwarning',
            name='target_contracts',
            field=models.TextField(blank=True, help_text='Separados por vírgula', null=True),
        ),
        migrations.AlterField(
            model_name='inappwarning',
            name='target_cpfs',
            field=models.TextField(blank=True, help_text='Separados por vírgula', null=True),
        ),
    ]
