# Generated by Django 6.0.2 on 2026-02-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_inappwarning_target_contracts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='dismissed_warnings',
            field=models.JSONField(blank=True, default=list, help_text='Lista de IDs de avisos que o usuário fechou'),
        ),
    ]
