# Generated by Django 5.2.4 on 2026-03-01 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_appuser_dismissed_warnings'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
