# Generated by Django 6.0.2 on 2026-03-29 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_appuser_avatar_appuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='speed_test_provider',
            field=models.CharField(choices=[('fast', 'Fast.com'), ('speedtest', 'Speedtest.net')], default='fast', max_length=20, verbose_name='Provedor de Speed Test'),
        ),
    ]
