# Generated by Django 6.0.2 on 2026-03-30 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_appconfig_speed_test_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='phone',
        ),
    ]
