# Generated by Django 6.0.2 on 2026-03-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_appuser_avatar_remove_appuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='last_active_at',
            field=models.DateTimeField(blank=True, help_text='Data e hora do último acesso geral do usuário', null=True),
        ),
    ]
