name: Build Android (APK & AAB)

on:
  workflow_dispatch: # Permite disparar manualmente
  push:
    branches:
      - master

jobs:
  build-android:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./react_native_space

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'npm'
          cache-dependency-path: react_native_space/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Inject API Token
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
        run: |
          sed -i "s/TOKEN_INTEGRACAO_PROVEDOR/$API_TOKEN/g" src/config/index.ts

      - name: Decode Keystore
        env:
          ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
        run: |
          echo "$ANDROID_KEYSTORE_BASE64" | base64 --decode > android/app/niochat-global.keystore

      - name: Build Android Release (AAB & APK)
        env:
          NANET_UPLOAD_STORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          NANET_UPLOAD_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
          NANET_UPLOAD_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
        run: |
          cd android
          chmod +x gradlew
          ./gradlew bundleRelease assembleRelease

      - name: Upload AAB Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-bundle
          path: react_native_space/android/app/build/outputs/bundle/release/app-release.aab

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: react_native_space/android/app/build/outputs/apk/release/app-release.apk
